### ISSUE TITLE
🐛 [bug] - Passwords containing %,#,// break a Jenkins pipeline

### ISSUE THREAD

**Issue by eformat** [rht-labs/tech-exercise#65] opened 2021-12-15 22:11 UTC
During testing ....

At the end of https://rht-labs.com/tech-exercise/#/2-attack-of-the-pipelines/3a-jenkins , this bit of the pipeline fails:

```
git clone https://${GIT_CREDS}@${ARGOCD_CONFIG_REPO} config-repo
```
with:
```
fatal: unable to access 'https://gitlab-ce.apps.tl500-1.ls-eu.ole.redhat.com/fulanitos/tech-exercise.git/': Port number ended with 'X'
```
that is likely caused by my password containing X followed by two :.

**Comment by alexpdp7** [comment] 2021-12-16 16:11
https://github.com/rht-labs/pet-battle/blob/51b673beec5b5ce70afdfd984901188ad50640a7/Jenkinsfile#L185
https://github.com/rht-labs/pet-battle/blob/51b673beec5b5ce70afdfd984901188ad50640a7/Jenkinsfile#L204

**Comment by alexpdp7** [comment] 2021-12-20 18:14
https://github.com/rht-labs/tech-exercise/blame/main/docs/5-the-deployments-strike-back/2-blue-green-deployments.md#L101
https://github.com/rht-labs/tech-exercise/blame/main/docs/5-the-deployments-strike-back/2-blue-green-deployments.md#L112
https://github.com/rht-labs/tech-exercise/blame/main/docs/5-the-deployments-strike-back/2-blue-green-deployments.md#L130

**Comment by alexpdp7** [comment] 2022-02-16 17:08
Hi, I really don't know- I just tried to locate the bits in the pipeline that failed, but I really don't have much say over that Jenkinsfile.

Personally, I'd go with making the passwords only use "trouble-free" characters. It's easier and clearer, and should prevent regressions of this issue, even if fixes are made now.

**Comment by eformat** [comment] 2022-02-16 21:55
@paulbarfuss - yeah this is fiddly in Jenkins world. i agree a trouble free password - or even better a trouble free gitlab token may be easier. @springdo @ckavili - this is in the pet-battle Jenkinsfile which you have the most familiarity with - got any thoughts here. is there an easy fix ?

**Comment by oybed** [comment] 2022-05-04 21:46
+100 
Please add some priority to get this addressed. We don't want any environments exposed to the public internet be forced to using simple passwords because of Jenkins.

**Comment by pabrahamsson** [comment] 2022-05-06 21:06
I did a bit of testing to see what options we might have for resolving this issue. In no particular order....

1. Use gitlab tokens
    - Fairly easy to create
    - Can be reset by the student
2. Url encode the gitlab password

**Comment by eformat** [comment] 2022-05-06 21:46
hey @pabrahamsson .. xkcd solved this for us 

![password_strength](https://user-images.githubusercontent.com/712608/167219777-f07fcbca-26bc-419d-81de-7a16e2b95d22.png)

one argument against gitlab tokens is that we end up creating multiple credentials for gitlab. not all learners are technical, so not having the complexity of adding token generation is appealing (this is not a "how to harden your security" course). as well, we would want to make the same changes for Tekton to be consistent.

URL encoding - i dont believe it is so simple,mainly because of the interactions between how we get users to copy-n-paste code in CRW, entering stuff on the CLI and the Jenkins shell.

my preference would be to stop doing this, [infra-ansible/roles/identity-management/manage-user-password/defaults](https://github.com/redhat-cop/infra-ansible/blob/main/roles/identity-management/manage-user-password/defaults/main.yml#L17) and instead have an XKCD inspired password that users can remember easily.

What Do You Think ?

**Comment by pabrahamsson** [comment] 2022-05-06 22:08
@eformat I must somehow have hit submit before finishing what I wanted to share. I've updated my previous comment above.

My preference would be that we can support any type of complexity for passwords but this is also where I would like to hear from others (such as you) who are more familiar with the flow of the class.
The copy-paste example is one of those things I wasn't sure about but can see could be an issue. And also Tekton  (are complex passwords not an issue there, or we just haven't run into them?), which I haven't looked into yet (just started looking through this today).

**Comment by eformat** [comment] 2022-05-06 22:24
Yeah, Tekton is actually all good - and just using single quote characters usually suffices (on the CLI) for example. 
The Jenkinsfile and jenkins shell, and some of its assumptions is really whats causing this issue.

In practice, we have been resetting user passwords to "correcthorsebatterystaple" ... cause it takes 5min's in IPA !!

my first preference would be to fix the Jenkinsfile - i have tried and failed. 
the people who wrote the Jenkinsfile (@springdo and @ckavili) moved to tokens originally, then we reverted it - cause is adds more complexity to the workflow !

so, here we are :)

**Comment by pabrahamsson** [comment] 2022-05-07 09:44
@eformat I've taken a stab at updating the Jenkinsfile over [here](https://github.com/pabrahamsson/pet-battle/blob/jenkinsfile-declarative-git/Jenkinsfile) (and [diff](https://github.com/rht-labs/pet-battle/compare/main...pabrahamsson:jenkinsfile-declarative-git?expand=1)).
I haven't had time to test this in a tl500 environment yet but it works well with the Jenkins and Gitlab instances I have used for testing. Thoughts?

**Comment by eformat** [comment] 2022-05-08 22:26
thanks petter @pabrahamsson  .. i have started to test this out

**Comment by eformat** [comment] 2022-05-08 22:46
rather annoyingly, the first password i try - cannot login to gitlab web (works ok on CLI and logging into OCP) via ldap

this is another sort of failure !

```
@This#Is//Not\\My,P@ssw0rd.
```

![Screenshot from 2022-05-09 08-19-56](https://user-images.githubusercontent.com/712608/167318884-b52ea034-3eb6-46c6-a4d9-2f16e409b178.png)

**Comment by eformat** [comment] 2022-05-09 00:20
OK @pabrahamsson .. after a bit of messing about .. this seems to fail on the clone when using the following details - can you see anything obviously wrong here ?

user specific details:
```
user: student3
password: @This#Is//Not\\My,P@ssw0rd.
```

build log in jenkins, i have obfuscated the full url as i am giving creds above, but it is the correct url:

![Screenshot from 2022-05-09 09-56-12](https://user-images.githubusercontent.com/712608/167321141-f97fda69-bb15-49e8-a0ee-1b7a24113bab.png)

the gitlab project 'test-repo' is set to "Internal" so you must login, and i can view it OK from gitlab webui as 'student3' who is an owner:

![Screenshot from 2022-05-09 09-52-39](https://user-images.githubusercontent.com/712608/167321224-d0ded93a-50e8-488a-bf5d-e1add33281e6.png)

![Screenshot from 2022-05-09 10-06-04](https://user-images.githubusercontent.com/712608/167321441-c5765396-fe4a-41fd-a70b-5f1268fd45c6.png)

my Jenkinsfile has this in it as per your change using 'withCredentials'

```
        stage('test creds') {
            steps {
                withCredentials([gitUsernamePassword(credentialsId: "${OPENSHIFT_BUILD_NAMESPACE}-git-auth", gitToolName: 'Default')]) {
                    sh  '''
                        printenv
                        rm -rf test-repo
                        git clone https://${REPO}
                        cd test-repo
                        git checkout master
                        echo "foobar" >> README.md
                        # Commit the changes :P
                        git config --global user.email "jenkins@rht-labs.bot.com"
                        git config --global user.name "Jenkins"
                        git config --global push.default simple
                        git add README.md
                        git commit -m "🚀 AUTOMATED COMMIT - Deployment of ${APP_NAME} at version ${VERSION} 🚀" || rc=$?
                        git remote set-url origin  https://${REPO}
                        git push -u origin master
                    '''
                }
            }
        }
```

I can login to OCP, GitLab OK from CLI and Web.
The git-auth secret looks OK in ArgoCD and from CLI, so sealed secret working

```
$ oc whoami
student3

$ oc -n ${TEAM_NAME}-ci-cd get secret git-auth -o jsonpath='{.data.username}' | base64 -d
student3

$ oc -n ${TEAM_NAME}-ci-cd get secret git-auth -o jsonpath='{.data.password}' | base64 -d
@This#Is//Not\\My,P@ssw0rd.
```

Secret has been synced into Jenkins (based on the label) OK

![Screenshot from 2022-05-09 09-46-35](https://user-images.githubusercontent.com/712608/167321248-45438f86-8cf9-4c15-a1a2-d82b51566f6e.png)

**Comment by eformat** [comment] 2022-05-09 00:40
and checking the Jenkins script console ... password actually looks OK, so could be the withCredentials plugin perhaps 

![Screenshot from 2022-05-09 10-35-31](https://user-images.githubusercontent.com/712608/167322808-3960c7e3-6fa1-4c68-8ecb-2074b5f95762.png)

**Comment by eformat** [comment] 2022-05-09 01:10
> hey @pabrahamsson .. xkcd solved this for us

for reference, we could optionally set an "xkcd" type password here:

https://github.com/eformat/infra-ansible/blob/main/roles/identity-management/manage-user-password/tasks/generate-password.yml#L9

Using:

https://docs.ansible.com/ansible/latest/collections/community/general/random_words_lookup.html

based on https://github.com/redacted/XKCD-password-generator

`ansible`
```xml
- name: Generate password with six, five character, words
  ansible.builtin.debug:
    var: lookup('community.general.random_words', min_length=5, max_length=5)
  # Example result: 'brink banjo getup staff trump comfy'
```

`shell`
```bash
$ xkcdpass --count=5 --acrostic='devops' --delimiter='|' --min=5 --max=6 --valid-chars='[a-z]'
dimple|enrage|venue|outage|pasty|sprang
ditzy|errand|viper|ounce|paced|sesame
depose|equity|violin|olive|phoney|snuff
decal|emcee|valium|octane|prissy|stray
deploy|editor|visor|output|patchy|salute
```

**Closed** 2022-05-27 09:32 UTC
Labels: bug
