### ISSUE TITLE
🐛 [bug] - Exercise with Kibana is not working as described

### ISSUE THREAD

**Issue by fc7** [rht-labs/tech-exercise#185] opened 2022-07-08 09:01 UTC
### 📝 Description
The exercise described [here](https://rht-labs.com/tech-exercise/#/4-return-of-the-monitoring/3-logging) is not working as expected. After creating the index pattern for `app-*` and field `@timestamp` the index is created, but whenever one visits the [Discover page](https://kibana-openshift-logging.apps.sabadell-2.ls-eu.ole.redhat.com/app/kibana#/discover?_g=()) one is being systematically redirected to the index creation step.

### 🚶 Steps to reproduce
Just repeat the instructions provided on [this Kibana instance](https://kibana-openshift-logging.apps.sabadell-2.ls-eu.ole.redhat.com)

**Comment by eformat** [comment] 2022-07-10 23:48
OK.. i have created an RHPDS TL500 cluster OK (so new cluster, new TL500 tooling)

Kibana logging working ok for me i.e. i could not reproduce this.

![Screenshot from 2022-07-11 09-46-03](https://user-images.githubusercontent.com/712608/178166691-30ed0b14-eb35-4edb-95bc-1442aa62c463.png)

![Screenshot from 2022-07-11 09-46-11](https://user-images.githubusercontent.com/712608/178166699-e312d004-3d8a-445e-88a7-db1dc546d576.png)

![Screenshot from 2022-07-11 09-46-23](https://user-images.githubusercontent.com/712608/178166702-1c3bdf51-1f90-4f75-8fb2-8bb06fd86f79.png)

Please feel free to reopen if you can debug more in your environment.

**Comment by eformat** [comment] 2022-07-10 23:49
closing for now. could not reproduce.

**Closed** 2022-07-10 23:49 UTC
Labels: bug

**Comment by fc7** [comment] 2022-07-11 07:29
On our cluster the problem still persists. @rmarting any chance you can have a look to understand the root cause?

**Comment by rmarting** [comment] 2022-07-11 08:25
I tested this exercise in a new and fresh OpenShift cluster and it is working as expected.

@fc7 :thinking: It seems that the cluster you are working on is not in the best situation. It could be a side effect of the stability issues during the week. I am not sure if we can find the root cause of this issue at this point. I agree with @eformat to close the issue for now and let's see if it is reproducible in the future.
